# Generated by Django 5.2.17 on 2026-10-04 13:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('core', '0002_part_partparam_project_part_project_inventorylot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_type', models.CharField(choices=[('requirement', 'requirement'), ('part', 'part'), ('supplier', 'supplier'), ('bom', 'bom'), ('bom_item', 'bom_item'), ('inventory_lot', 'inventory_lot'), ('work_order', 'work_order'), ('purchase_order', 'purchase_order'), ('test_case', 'test_case'), ('test_run', 'test_run'), ('ecn', 'ecn'), ('document', 'document'), ('git_commit', 'git_commit')], max_length=32)),
                ('from_id', models.CharField(max_length=64)),
                ('to_type', models.CharField(choices=[('requirement', 'requirement'), ('part', 'part'), ('supplier', 'supplier'), ('bom', 'bom'), ('bom_item', 'bom_item'), ('inventory_lot', 'inventory_lot'), ('work_order', 'work_order'), ('purchase_order', 'purchase_order'), ('test_case', 'test_case'), ('test_run', 'test_run'), ('ecn', 'ecn'), ('document', 'document'), ('git_commit', 'git_commit')], max_length=32)),
                ('to_id', models.CharField(max_length=64)),
                ('relation_type', models.CharField(choices=[('derived_from', 'derived_from'), ('satisfied_by', 'satisfied_by'), ('implemented_by', 'implemented_by'), ('verified_by', 'verified_by'), ('documented_by', 'documented_by'), ('ordered_by', 'ordered_by'), ('sourced_from', 'sourced_from'), ('tested_by', 'tested_by'), ('affected_by', 'affected_by'), ('affects', 'affects'), ('evidences', 'evidences'), ('allocates', 'allocates'), ('replaces', 'replaces'), ('supersedes', 'supersedes'), ('references', 'references')], max_length=32)),
                ('source', models.CharField(choices=[('manual', 'manual'), ('agent', 'agent'), ('import', 'import')], default='manual', max_length=16)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('evidence', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trace_links', to='agents.agentrun')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_trace_links', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trace_links', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trace_links', to='core.project')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['project', 'from_type', 'from_id'], name='ix_tracelink_from'), models.Index(fields=['project', 'to_type', 'to_id'], name='ix_tracelink_to'), models.Index(fields=['project', 'relation_type'], name='ix_tracelink_relation'), models.Index(fields=['agent_run'], name='ix_tracelink_agent_run'), models.Index(fields=['confirmed_by'], name='ix_tracelink_confirmed_by')],
                'constraints': [models.UniqueConstraint(fields=('project', 'from_type', 'from_id', 'to_type', 'to_id', 'relation_type'), name='uq_tracelink_edge')],
            },
        ),
    ]
