# Generated by Django 5.2.17 on 2026-10-04 13:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(choices=[('requirement', 'requirement'), ('bom_selection', 'bom_selection'), ('traceability', 'traceability')], max_length=32)),
                ('status', models.CharField(choices=[('failed', 'failed'), ('needs_review', 'needs_review'), ('success', 'success'), ('rejected', 'rejected')], max_length=16)),
                ('prompt_id', models.CharField(max_length=100)),
                ('prompt_version', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=64)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=3)),
                ('input_json', models.JSONField()),
                ('input_hash', models.CharField(max_length=64)),
                ('output_json', models.JSONField(blank=True, null=True)),
                ('output_schema_valid', models.BooleanField(blank=True, null=True)),
                ('reference_check_passed', models.BooleanField(blank=True, null=True)),
                ('invalid_references', models.JSONField(blank=True, null=True)),
                ('references', models.JSONField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_agent_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
