# Generated by Django 5.2.17 on 2026-10-04 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('core', '0002_part_partparam_project_part_project_inventorylot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='core.project'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['project', 'agent_name', 'status'], name='ix_agentrun_proj_agent_status'),
        ),
    ]
