# Generated by Django 5.2.17 on 2026-10-04 13:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('mpn', models.CharField(blank=True, max_length=200)),
                ('lifecycle_status', models.CharField(choices=[('active', 'active'), ('nrnd', 'nrnd'), ('eol', 'eol'), ('obsolete', 'obsolete')], default='active', max_length=16)),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('is_critical', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PartParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value_text', models.CharField(blank=True, max_length=255)),
                ('value_num', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('value_min', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('value_max', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('is_key', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='core.part')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('archived', 'archived')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='part',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='core.project'),
        ),
        migrations.CreateModel(
            name='InventoryLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_type', models.CharField(choices=[('lot', 'lot'), ('serial', 'serial')], default='lot', max_length=8)),
                ('serial_number', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('qty_available', models.DecimalField(decimal_places=4, max_digits=18)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('available', 'available'), ('allocated', 'allocated'), ('consumed', 'consumed'), ('scrapped', 'scrapped')], default='available', max_length=16)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_lots', to='core.part')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_lots', to='core.project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GitRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('local_path', models.CharField(max_length=500)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('default_branch', models.CharField(blank=True, max_length=100)),
                ('is_readonly', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_repos', to='core.project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GitCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=40)),
                ('author_name', models.CharField(blank=True, max_length=100)),
                ('author_email', models.CharField(blank=True, max_length=254)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='core.gitrepo')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_commits', to='core.project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ECN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecn_number', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('change_type', models.CharField(blank=True, choices=[('design', 'design'), ('material', 'material'), ('process', 'process'), ('documentation', 'documentation')], max_length=32)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('reviewing', 'reviewing'), ('approved', 'approved'), ('rejected', 'rejected'), ('implemented', 'implemented')], default='draft', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecns', to='agents.agentrun')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ecns', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_ecns', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecns', to='core.project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_no', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=300)),
                ('doc_type', models.CharField(choices=[('drawing', 'drawing'), ('prd', 'prd'), ('sor', 'sor'), ('email', 'email'), ('test_report', 'test_report'), ('other', 'other')], max_length=32)),
                ('file_path', models.CharField(max_length=500)),
                ('source_path', models.CharField(blank=True, max_length=500)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('is_readonly', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bom_no', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('released', 'released'), ('obsolete', 'obsolete')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_boms', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='core.project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('prd', 'prd'), ('sor', 'sor'), ('email', 'email'), ('manual', 'manual')], default='manual', max_length=16)),
                ('source_ref', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('pending_confirmation', 'pending_confirmation'), ('confirmed', 'confirmed'), ('rejected', 'rejected'), ('implemented', 'implemented')], default='draft', max_length=24)),
                ('priority', models.CharField(blank=True, choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], max_length=8, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='agents.agentrun')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_requirements', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='core.project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RequirementParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('operator', models.CharField(choices=[('eq', 'eq'), ('gte', 'gte'), ('lte', 'lte'), ('range', 'range')], default='eq', max_length=8)),
                ('value_text', models.CharField(blank=True, max_length=255)),
                ('value_num', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('value_min', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('value_max', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='core.requirement')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='core.project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('open', 'open'), ('partial', 'partial'), ('received', 'received'), ('closed', 'closed'), ('cancelled', 'cancelled')], default='draft', max_length=16)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='CNY', max_length=8)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='core.project')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='core.supplier')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_part_number', models.CharField(blank=True, max_length=100)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('currency', models.CharField(default='CNY', max_length=8)),
                ('lead_time_days', models.IntegerField(blank=True, null=True)),
                ('moq', models.IntegerField(blank=True, null=True)),
                ('is_preferred', models.BooleanField(default=False)),
                ('lifecycle_status', models.CharField(choices=[('active', 'active'), ('nrnd', 'nrnd'), ('eol', 'eol'), ('obsolete', 'obsolete')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_parts', to='core.part')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_parts', to='core.supplier')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('test_type', models.CharField(blank=True, choices=[('electrical', 'electrical'), ('thermal', 'thermal'), ('emc', 'emc'), ('environmental', 'environmental'), ('functional', 'functional')], max_length=32)),
                ('precondition', models.TextField(blank=True)),
                ('expected', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('deprecated', 'deprecated')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='core.project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_no', models.CharField(max_length=64)),
                ('sample_serial', models.CharField(blank=True, max_length=100)),
                ('result', models.CharField(choices=[('pass', 'pass'), ('fail', 'fail'), ('blocked', 'blocked'), ('skipped', 'skipped')], max_length=16)),
                ('tested_at', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='core.project')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.testcase')),
                ('tester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('status', models.CharField(choices=[('planned', 'planned'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='planned', max_length=16)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='core.bom')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_orders', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='core.project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ECNImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affected_type', models.CharField(choices=[('requirement', 'requirement'), ('part', 'part'), ('supplier', 'supplier'), ('bom', 'bom'), ('bom_item', 'bom_item'), ('inventory_lot', 'inventory_lot'), ('work_order', 'work_order'), ('purchase_order', 'purchase_order'), ('test_case', 'test_case'), ('test_run', 'test_run'), ('ecn', 'ecn'), ('document', 'document'), ('git_commit', 'git_commit')], max_length=32)),
                ('affected_id', models.CharField(max_length=64)),
                ('impact_type', models.CharField(blank=True, choices=[('affected', 'affected'), ('blocked', 'blocked'), ('replace_required', 'replace_required')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ecn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='core.ecn')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['ecn'], name='ix_ecnimpact_ecn'), models.Index(fields=['affected_type', 'affected_id'], name='ix_ecnimpact_affected')],
            },
        ),
        migrations.CreateModel(
            name='BomItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(max_length=64)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=18)),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('ref_des', models.CharField(blank=True, max_length=255)),
                ('position', models.CharField(blank=True, max_length=64)),
                ('is_critical', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.bom')),
                ('parent_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.bomitem')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_items', to='core.part')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('bom', 'item_no'), name='uq_bomitem_bom_item_no')],
            },
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['project', 'lifecycle_status'], name='ix_part_project_lifecycle'),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.UniqueConstraint(fields=('project', 'part_number'), name='uq_part_project_number'),
        ),
        migrations.AddIndex(
            model_name='inventorylot',
            index=models.Index(fields=['part', 'status'], name='ix_inventorylot_part_status'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.UniqueConstraint(fields=('project', 'serial_number'), name='uq_inventorylot_project_serial'),
        ),
        migrations.AddConstraint(
            model_name='gitrepo',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uq_gitrepo_project_name'),
        ),
        migrations.AddIndex(
            model_name='gitcommit',
            index=models.Index(fields=['committed_at'], name='ix_gitcommit_committed_at'),
        ),
        migrations.AddConstraint(
            model_name='gitcommit',
            constraint=models.UniqueConstraint(fields=('repo', 'sha'), name='uq_gitcommit_repo_sha'),
        ),
        migrations.AddConstraint(
            model_name='ecn',
            constraint=models.UniqueConstraint(fields=('project', 'ecn_number'), name='uq_ecn_project_ecn_number'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['project', 'doc_type'], name='ix_document_project_type'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['checksum'], name='ix_document_checksum'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('project', 'doc_no'), name='uq_document_project_doc_no'),
        ),
        migrations.AddConstraint(
            model_name='bom',
            constraint=models.UniqueConstraint(fields=('project', 'bom_no'), name='uq_bom_project_bom_no'),
        ),
        migrations.AddConstraint(
            model_name='bom',
            constraint=models.UniqueConstraint(fields=('project', 'version'), name='uq_bom_project_version'),
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='uq_requirement_project_code'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='uq_supplier_project_code'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier', 'status'], name='ix_po_supplier_status'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('project', 'po_number'), name='uq_purchaseorder_project_po'),
        ),
        migrations.AddConstraint(
            model_name='supplierpart',
            constraint=models.UniqueConstraint(fields=('supplier', 'part'), name='uq_supplierpart_supplier_part'),
        ),
        migrations.AddConstraint(
            model_name='testcase',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='uq_testcase_project_code'),
        ),
        migrations.AddIndex(
            model_name='testrun',
            index=models.Index(fields=['test_case'], name='ix_testrun_test_case'),
        ),
        migrations.AddIndex(
            model_name='testrun',
            index=models.Index(fields=['result'], name='ix_testrun_result'),
        ),
        migrations.AddConstraint(
            model_name='testrun',
            constraint=models.UniqueConstraint(fields=('project', 'run_no'), name='uq_testrun_project_run_no'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='uq_workorder_project_code'),
        ),
    ]
