# Generated by Django 5.2.17 on 2026-10-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_part_partparam_project_part_project_inventorylot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='lifecycle_status',
            field=models.CharField(choices=[('active', 'active'), ('nrnd', 'nrnd'), ('eol', 'eol'), ('obsolete', 'obsolete'), ('discontinued', 'discontinued')], default='active', max_length=16),
        ),
    ]
