# Generated by Django 5.2.17 on 2026-10-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_part_lifecycle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='substitute_group',
            field=models.CharField(blank=True, default='', help_text='替代料组标签（同组候选可互换），如 SG-SEL-<agent_run_id>（D6-R3 受控扩展，见 ADR-0012）', max_length=64),
        ),
    ]
